name: Deploy to AWS CodeDeploy

on:
  push:
    branches: [release]

env:
  PROJECT_NAME: issueTracker
  BUCKET_NAME: issuetrackerbucket
  CODE_DEPLOY_APP_NAME: issueTracker-app
  DEPLOYMENT_GROUP_NAME: issueTrackerGroup
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env : 
      APPLICATION: ${{ secrets.APPLICATION }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - uses: actions/setup-java@v2
      - run: touch ./backend/src/main/resources/application.properties
      - run: echo "${{ secrets.APPLICATION }}" > ./backend/src/main/resources/application.properties
      - run: cat ./backend/src/main/resources/application.properties

      - name: Build JAR
        run: |
          cd backend
          chmod +x gradlew
          ./gradlew clean build
          
      - name: Make Directory for deliver
        run: mkdir deploy

      - name: Copy Jar
        run: cp ./backend/build/libs/*.jar ./deploy/

      - name: Make zip file
        run: zip -r -qq -j ./issueTracker-build.zip ./deploy

      - name: Upload ZIP to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
          src: ./issueTracker-build.zip
          dest: s3://${{ env.BUCKET_NAME }}/issueTracker-build.zip
        env:
          AWS_S3_BUCKET: ${{ env.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to CodeDeploy
        run: aws deploy create-deployment --application-name ${{ env.CODE_DEPLOY_APP_NAME }} --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} --s3-location bucket=${{ env.BUCKET_NAME }},bundleType=zip,key=issueTracker-build.zip
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
