name: Deploy to AWS CodeDeploy

on:
  push:
    branches: [ test ]

env:
  PROJECT_NAME: issueTracker
  BUCKET_NAME: issuetrackerbucket
  CODE_DEPLOY_APP_NAME: issueTracker-app
  DEPLOYMENT_GROUP_NAME: issueTrackerGroup

jobs:
  was-build-and-deploy:
    runs-on: ubuntu-latest
    env:
      APPLICATION: ${{ secrets.APPLICATION }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - run: |
          touch ./backend/src/main/resources/application.yml
          echo "${{ secrets.APPLICATION }}" > ./backend/src/main/resources/application.yml
          cat ./backend/src/main/resources/application.yml

      - name: Build JAR
        run: |
          cd backend
          chmod +x gradlew
          ./gradlew clean build

      - name: Make Directory for deliver
        run: mkdir -p deploy/was

      - name: Copy Jar, appspec.yml and deploy.sh
        run: |
          cp ./backend/build/libs/*.jar ./deploy/
          cp ./appspec-was.yml ./deploy/appspec.yml
          cp ./deploy-was.sh ./deploy/

      - name: Make zip file
        run: zip -r ./issueTracker-build.zip ./deploy/

      - name: Upload ZIP to S3
        run: |
          aws s3 cp ./issueTracker-build.zip s3://${{ env.BUCKET_NAME }}/deploy/was/issueTracker-build.zip
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Wait for previous deployment to finish
        run: |
          while [[ "$(aws deploy list-deployments --include-only-statuses InProgress --application-name ${{ env.CODE_DEPLOY_APP_NAME }} --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} | jq '.deployments | length')" -ne 0 ]]; do
            echo "Deployment in progress, waiting..."
            sleep 60
          done
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APP_NAME }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ env.BUCKET_NAME }},bundleType=zip,key=deploy/was/issueTracker-build.zip
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  web-build-and-deploy:
    needs: was-build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build React App
        run: npm run build
        working-directory: ./frontend

      - name: Make Directory for deliver
        run: mkdir -p deploy/web

      - name: Copy build, appspec.yml and deploy.sh
        run: |
          cp -r ./frontend/build/ ./deploy/
          cp ./appspec-web.yml ./deploy/appspec.yml
          cp ./deploy-web.sh ./deploy/

      - name: Make zip file
        run: zip -r ./react-build.zip ./deploy/

      - name: Install jq
        run: sudo apt-get install jq

      - name: Assume Role
        run: |
          ROLE_ARN=arn:aws:iam::263514117796:role/was_root
          TEMP_ROLE=$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name GitHubActions --debug)
          export AWS_ACCESS_KEY_ID=$(echo $TEMP_ROLE | jq .Credentials.AccessKeyId | xargs)
          export AWS_SECRET_ACCESS_KEY=$(echo $TEMP_ROLE | jq .Credentials.SecretAccessKey | xargs)
          export AWS_SESSION_TOKEN=$(echo $TEMP_ROLE | jq .Credentials.SessionToken | xargs)
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN"
      

      - name: Upload ZIP to S3
        run: |
          aws s3 cp ./react-build.zip s3://${{ env.BUCKET_NAME }}/deploy/web/react-build.zip
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}

      - name: Wait for previous deployment to finish
        run: |
          while [[ "$(aws deploy list-deployments --include-only-statuses InProgress --application-name ${{ env.CODE_DEPLOY_APP_NAME }} --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} | jq '.deployments | length')" -ne 0 ]]; do
            echo "Deployment in progress, waiting..."
            sleep 60
          done
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}

      - name: Deploy to CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APP_NAME }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ env.BUCKET_NAME }},bundleType=zip,key=deploy/web/react-build.zip
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
