name: Deploy to AWS CodeDeploy

on:
  push:
    branches: [ release ]

env:
  PROJECT_NAME: issueTracker
  BUCKET_NAME: issuetrackerbucket
  CODE_DEPLOY_APP_NAME: issueTracker-app
  DEPLOYMENT_GROUP_NAME: issueTrackerGroup

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Build JAR
        run: |
          cd backend
          chmod +x gradlew
          ./gradlew build --exclude-task test

      - name: Upload JAR to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
          src: backend/build/libs/*.jar
        env:
          AWS_S3_BUCKET: issuetrackerbucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to CodeDeploy
        run: aws deploy create-deployment --application-name ${{ env.CODE_DEPLOY_APP_NAME }} --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} --s3-location bucket=${{ env.BUCKET_NAME }},bundleType=jar,key=backend/build/libs/*.jar
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
